### ISSUE TITLE
Web access

### ISSUE THREAD

**Issue by AugustooRibeiroo** [globocom/GloboDNS#10]
Sorry for the ignorance haha
Performed the installation successfully GloboDNS, everything works.
The problem is that I do not know the User and default password to access the Web Panel.
Can someone help me ?

**Comment by anacarolinacastro** [comment]
Hi **augustoorjj**, the default admin user is created on step 8 at the [Setup your environment](https://github.com/globocom/GloboDNS/blob/master/doc/setup.md) documentation.

email: _admin@example.com_
password:  _password_

**Comment by AugustooRibeiroo** [comment]
Ok, it really was an oversight.
Worked perfectly thank you @anacarolinacastro !
