### ISSUE TITLE
no rndc key found in master's named.conf

### ISSUE THREAD

**Issue by YangTao0** [globocom/GloboDNS#24]
Hello guys !
When I executed the command on globodns server,  ruby script/importer --remote     there was an error.

globodns server error:
no rndc key found in master's named.conf
no rndc key found in master's named.conf
[ERROR] import failed
DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job. (called from rescue in import at /home/tao.yang02/globodns/lib/globo_dns/importer.rb:272)
  Rendered notifier/import_failed.en.text.erb (2.1ms)

my bind server named.conf
/var/named/chroot/etc/named.conf
options {
         directory "/var/named";
         pid-file "/run/named/named.pid";
	 statistics-file "/var/named/data/named.stats";
	 notify no;
	 version "xxxxxxxxxx";
	 check-names master warn;
	 zone-statistics yes;             
	 edns-udp-size 4096;
	 max-ncache-ttl 300;
         forwarders  { NN.NN.NN.NN;
		       NN.NN.NN.NN; 
         };
	 allow-query { any; };
};
logging { 
category lame-servers { null; };
channel warning
{ 
file "/var/log/named.log" versions 3 size 204800k; 
severity info;
print-category yes;
print-severity yes;
print-time yes;
}
;
channel query
{ 
file "/var/log/query.log" versions 3 size 204800k;
severity info;
print-category yes;
print-severity yes;
print-time yes;
}
;
channel security
{
file "/var/log/security.log" versions 3 size 204800k;
severity info;
print-category yes;
print-severity yes;
print-time yes;
}
;
category default { warning; };
category queries { query; };
category security { security; };
};
include "/etc/init_zone.conf";
key "rndc-key" {
      algorithm hmac-md5;
      secret "XXXXXXXXXXXXX";
};
controls {
      inet 10.104.114.45 port 953
      allow { 127.0.0.1;10.104.114.45; } keys { "rndc-key"; };
};

How can I solve this problem? I look forward to your reply. Thank you.

**Comment by linux-ops** [comment]
well well ···

**Comment by ernestothorp** [comment]
Please check if the key name on your named.conf file is the same set on globodns.yml on the `:rndc_key_name ` parameter.

**Comment by YangTao0** [comment]
@ernestothorp  Thank you for your reply.The problem has been solved. You're right，my globodns.yml is wrong.
