### ISSUE TITLE
Name is invalid

### ISSUE THREAD

**Issue by YangTao0** [globocom/GloboDNS#26]
Hello,when I edit the record,web display Name is invalid，but others domain is right.

Started PATCH "/records/220390" for 127.0.0.1 at 2019-04-21 19:31:01 +0800
Processing by RecordsController#update as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"DrIZygunSbffLPwu0moYxrv8pXpin11+5JQvb1x6mFLJGuQSjx0uXUPr+cmKIrlTSYM+xxFj5tzmEKeKejZFfQ==", "record"=>{"name"=>"123.10101111.com.", "ttl"=>"601", "range"=>"", "content"=>"10.204.250.141"}, "id"=>"220390"}
{"name"=>"123.10101111.com.", "ttl"=>"601", "range"=>"", "content"=>"10.204.250.141"}
  Rendered records/_errors.html.haml (0.6ms)
Completed 422 Unprocessable Entity in 38ms (Views: 1.7ms | ActiveRecord: 2.5ms)

Started PATCH "/records/222788" for 127.0.0.1 at 2019-04-21 16:39:44 +0800
Processing by RecordsController#update as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"e2YMckL5m73DAJdb4uyxjry8YObXz34zN4AyR/e+ujm8zvGqxkP8V1/Hkry6pBAbTsP7W6QzxZE1BLqi0fJnFg==", "record"=>{"name"=>"aicoupon.luckincoff
ee.com.", "ttl"=>"300", "range"=>"", "content"=>"10.204.250.233"}, "id"=>"222788"}
{"name"=>"aicoupon.luckincoffee.com.", "ttl"=>"300", "range"=>"", "content"=>"10.204.250.233"}
  Rendered records/_record.html.haml (17.7ms)
Completed 200 OK in 62ms (Views: 19.8ms | ActiveRecord: 3.5ms)

**Comment by ernestothorp** [comment]
Hi,
Thank you for you message.
This is done in [app/model/record.rb](https://github.com/globocom/GloboDNS/blob/master/app/models/record.rb#L484), where we disallow a hostname only with numbers.
`unless (index == 0 && part == '*') || part =~ /^(?![0-9]+$)(?!\-)[a-zA-Z0-9\-.]{,63}(?<!\-)$/`
This was in the original request for this project. If you would like, you can open a PR removing this restriction `(?![0-9]+$)`.

**Comment by YangTao0** [comment]
@ernestothorp Thank you very much. You solved my problem.
