### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by moondal** [globocom/GloboDNS#9]
erroe message

web 

Application error
Rails application failed to start properly

It was along the same error occurs.
Please contact what to proceed with the installation again in any part .

help...

**Comment by marceloboeira** [comment]
@moondal can you please provide more information? (Such as the steps to reproduce, stack trace).

**Comment by moondal** [comment]
hi If you proceed with the test it does not respond .  this is "httpd.conf" <VirtualHost *:80>    ServerName ansible0101    DocumentRoot /home/globodns/globodns/public    <Directory /home/globodns/globodns/public>      AllowOverride all      Options -MultiViews    </Directory></VirtualHost>
------ Original Message ------
Date: Thursday, Apr 21, 2016 03:21:40 AM

**Comment by moondal** [comment]
httpd error log is
(2)No such file or directory: exec of '/home/globodns/globodns/public/dispatch.cgi' failed
Premature end of script headers: dispatch.cgi

**Comment by ernestothorp** [comment]
Have you followed all steps in https://github.com/globocom/GloboDNS/blob/master/doc/setup.md ?

I guess you are only using apache to run the application. This doesn't work. You'll need to run an application server such as unicorn (recommended) or passenger.

Your VHost should look like this:
```
<VirtualHost *:80>
    ServerName yourdomain.example

    # Tell Apache and Passenger where your app's 'public' directory is
    DocumentRoot /path-to-your-application/public

    RewriteEngine On

    <Proxy balancer://unicornservers>
      BalancerMember http://127.0.0.1:8080
    </Proxy>
    # Redirect all non-static requests to thin
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteRule ^/(.*)$ balancer://unicornservers%{REQUEST_URI} [P,QSA,L]

   # NOTE Uncomment if you want Unicorn to serve static content
   # ProxyPass / balancer://unicornservers/
   # ProxyPassReverse / balancer://unicornservers/
   # ProxyPreserveHost on

    <Proxy *>
      Order deny,allow
      Allow from all
    </Proxy>

</VirtualHost>
```

**Comment by anacarolinacastro** [comment]
@moondal it worked?
